### ISSUE TITLE
No skins can be found bug

### ISSUE THREAD

**Issue by Teague-S** [StiliyanKushev/csgo-tradeup-cli#8]
When running the command to look for trade-ups, I always get the "No skins can be found with the passed parameters! Aborting..." error.

**Comment by Teague-S** [comment]
Honestly, I have no clue how I fixed this, your code was broken in many parts.

**Comment by NORXONDOR** [comment]
> Honestly, I have no clue how I fixed this, your code was broken in many parts.

Do you still have no clue how you fixed it? I just found this program but it is either intuitive or broken to hell, because I keep getting the "No skins can be found with the passed parameters! Aborting..." error. I also can't save my database using --sdb, so a new one gets created everytime I run the program. I really wish there was some better documentation.

**Comment by StiliyanKushev** [comment]
No skins can be found, is most likely caused by one of two things.

1. You passed parameters that narrow the search to something so specific it doesn't exist.
2. Your database is empty, for whatever reason.

Keep in mind that you might be passing launch options that either clear the database or attempt to regenerate it each time. If that's not the case then it might be a faulty mongodb configuration. In any case, I am unable to reproduce your issue, so a step by step is likely required on your end.
